version: "3.9"

services:
  # reverse_proxy:
  #   image: nginx:latest
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   restart: always
  
  front: 
    image: diouxx/glpi
    restart: always
    ports:
      - "80:80"

  back:
    image: mariadb:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: diouxx
      MARIADB_DATABASE: glpidb
      MARIADB_USER: glpi_user
      MARIADB_PASSWORD: glpi

volumes:
  db_data: {}