FROM ubuntu

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get install -y apache2

COPY . /var/www/

#RUN cp -r /var/www/halcyonic/* /var/www/html

EXPOSE 80 443

CMD ["apachectl", "-D", "FOREGROUND"]
